export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = " FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = " FETCH_USERS_FAILURE";

export const USER_LOADING = " USER_LOADING";
export const GET_USER_BY_ID = " GET_USER_BY_ID";
export const GET_USER_BY_ID_FAILED = " GET_USER_BY_ID_FAILED";
export const  ONCLICK_ID='ONCLICK_ID';
 export const SET_USER='SET_USER';
export const UPDATE_PROFILE_SUCCESS='UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED='UPDATE_PROFILE_FAILED';

export const GET_USER_BILL_BY_ID = " GET_USER_BILL_BY_ID";
export const GET_USER_BILL_BY_ID_FAILED = " GET_USER_BILL_BY_ID_FAILED";

export const GET_SEARCH_USER = " GET_SEARCH_USER";
export const GET_SEARCH_USER_FAILED = " GET_SEARCH_USER_FAILED";