export const GET_PARTNER_CATEGORY = "GET_PARTNER_CATEGORY";
export const GET_PARTNER_CATEGORY_FAILED = "GET_PARTNER_CATEGORY_FAILED";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";
export const ADD_PARTNER_CATEGORY = "ADD_PARTNER_CATEGORY";
export const ADD_PARTNER_CATEGORY_FAILED = "ADD_PARTNER_CATEGORY_FAILED";
export const DELETE_PARTNER_CATEGORY = "DELETE_PARTNER_CATEGORY";
export const DELETE_PARTNER_CATEGORY_FAILED = "DELETE_PARTNER_CATEGORY_FAILED";
export const GET_PARTNER_CATEGORY_BY_ID = "GET_PARTNER_CATEGORY_BY_ID";
export const GET_PARTNER_CATEGORY_BY_ID_FAILED =
  "GET_PARTNER_CATEGORY_BY_ID_FAILED";
