export const FETCH_CREDITDETAILS_PROFILE = "FETCH_CREDITDETAILS_PROFILE";
export const FETCH_CREDITDETAILS_FAILURE = " FETCH_CREDITDETAILS_FAILURE";
export const FETCH_CREDITDETAILS_SUCCESS = " FETCH_CREDITDETAILS_SUCCESS";
