export const FETCH_PARTNER_REQUEST ='FETCH_PARTNER_REQUEST';
export const  FETCH_PARTNER_SUCCESS=' FETCH_PARTNER_SUCCESS';
export const  FETCH_PARTNER_FAILURE=' FETCH_PARTNER_FAILURE';
export const  ONCLICK_ID='ONCLICK_ID';
export const SET_PARTNER='SET_PARTNER';
export const UPDATE_PROFILE_SUCCESS='UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED='UPDATE_PROFILE_FAILED';