export const FETCH_SETTLEMENT_REQUEST ='FETCH_SETTLEMENT_REQUEST';
export const  FETCH_SETTLEMENT_SUCCESS=' FETCH_SETTLEMENT_SUCCESS';
export const  FETCH_SETTLEMENT_FAILURE=' FETCH_SETTLEMENT_FAILURE';
