export const FETCH_SETTLEMENT_REQUEST ='FETCH_SETTLEMENT_REQUEST';
export const  FETCH_SETTLEMENT_SUCCESS=' FETCH_SETTLEMENT_SUCCESS';
export const  FETCH_SETTLEMENT_FAILURE=' FETCH_SETTLEMENT_FAILURE';
export const PARTNERS_SETTLEMENTS_LOADING = "PARTNERS_SETTLEMENTS_LOADING";
export const SEARCH_SETTLEMENT = "SEARCH_SETTLEMENT";
export const SEARCH_SETTLEMENT_FAILED = "SEARCH_SETTLEMENT_FAILED";
