export const GET_BANK_DETAILS = "GET_BANK_DETAILS";
export const GET_BANK_DETAILS_FAILED = "GET_BANK_DETAILS_FAILED";
export const UPDATE_BANK = "UPDATE_BANK";
export const UPDATE_BANK_FAILED = "UPDATE_BANK_FAILED";
export const BANK_LOADING = "UPDATE_BANK_LOADING";