export const  FETCH_TRANSACTION_REQUEST ='FETCH_TRANSACTION_REQUEST';
export const  FETCH_TRANSACTION_SUCCESS ='FETCH_TRANSACTION_SUCCESS';
export const  FETCH_TRANSACTION_FAILURE ='FETCH_TRANSACTION_FAILURE';
export const GET_TRANSACTION_BY_ID = "GET_TRANSACTION_BY_ID";
export const GET_TRANSACTION_BY_ID_FAILED = "GET_TRANSACTION_BY_ID_FAILED";
export const PARTNERS_LOADING = "PARTNERS_LOADING";