export const FETCH_ALL_TICKETS = "FETCH_ALL_TICKETS";
export const FETCH_TICKETS_SUCCESS = " FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAILURE = " FETCH_TICKETS_FAILURE";
export const FETCH_TICKETS_LOADING = "FETCH_TICKETS_LOADING";
