export const CHECK_LOGIN = "check_login";
export const LOGIN_USER_SUCCESSFUL = "LOGIN_USER_SUCCESSFUL";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const VERIFY_LOADING = "VERIFY_LOADING";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const API_ERROR = "api_failed";
export const OTP_SENT = "OTP_SENT";
export const OTP_SENT_FAILED = "OTP_SENT_FAILED";
export const SHOW_OTP_MODAL = "SHOW_OTP_MODAL";
export const HIDE_OTP_MODAL = "HIDE_OTP_MODAL";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const CLEAR_ERROR = "CLEAR_ERROR";